### ISSUE TITLE
Greater than and less than symbols are in wrong order in example image

### ISSUE THREAD

**Issue by KasperiP** [samulisuomi/finsi#2]
Not sure if project is still maintained, but `<` & `>` symbols are in wrong order in example image when compared to current windows version layout. I have been using this layout since I got my ansi layout keyboard and this is fire <3

**Comment by samulisuomi** [comment]
Thanks for letting me know. 😅 

Because of this, I actually just realized these symbols are in the wrong order in my current keycap set too – which from now on will surely be triggering minor OCD every time I glance at the board. 🙈 

![155531868-4d8df4be-e256-41cb-9824-94b3a058708b](https://user-images.githubusercontent.com/3490745/155531868-4d8df4be-e256-41cb-9824-94b3a058708b.png)

Can't blame my keycaps for this though as I created that image a long before I got these.
